# site settings

title: Thulashitharan  
description: My personal website/blog
taglong: Multidisciplinary Engineer.
tagshort: Blog
url: https://supernovatux.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/supernovatux/supernovatux.github.io
show_projects_card: true
show_projects: true
projects_title: Projects
skills_title: Skills
#show_os_projects: true
#os_projects_title: Open Source Projects
# author settings

author:
  name: Thulashitharan D
  email: thulashitharan.d@gmail.com
photo: /assets/jpg/photo.jpeg

# social media links

social:
  github: supernovatux
  linkedin: thulashitharan-d-460172228

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
